Repository nestjs/swagger, pull requests merged in 2018-06, with the labels that each got.

#97 Update api-response.explorer.ts to properly reflect arrays of primatives
  lib/explorers/api-response.explorer.ts
  package-lock.json
  package.json
Labels: bugfix

#94 add deprecated param to operation model
  lib/decorators/api-operation.decorator.ts
  package-lock.json
  package.json
Labels: enhancement

#91 Update validateRoutePath to use Express's path-to-regexp lib
  lib/swagger-explorer.ts
  package.json
Labels: bug
