Repository nestjs/swagger, pull requests merged in 2019-07, with the labels that each got.

#253 [hotfix]: Fix Another Issue with Nest Router Package and Swagger Integration.
  lib/swagger-explorer.ts
Labels: bugfix, status: wip

#183 Add the very first test
  .gitignore
  package-lock.json
  package.json
  test/explorer/explore-controllers.spec.ts
Labels: enhancement

#155 Enable enum for @param's
  lib/decorators/api-implicit-param.decorator.ts
  yarn.lock
Labels: enhancement

#170 feature: add OpenAPI's nullable flag to APIModelProperty
  lib/decorators/api-model-property.decorator.ts
Labels: feature

#168 Fix for param type in docs for 'multipart/form-data' requests
  lib/explorers/api-parameters.explorer.ts
Labels: bugfix
