Repository nestjs/swagger, pull requests merged in 2024-10, with the labels that each got.

#2998 feat: make methods of swagger module protected
  lib/swagger-module.ts
Labels: enhancement

#2742 feat: refactoring and extending the support of validation property assignments
  lib/plugin/visitors/model-class.visitor.ts
  lib/services/decorators-properties.ts
  test/plugin/fixtures/create-cat.dto.ts
Labels: feature

#3029 fix: properly import external enums
  lib/plugin/utils/external-imports.util.ts
  lib/plugin/visitors/model-class.visitor.ts
  test/plugin/fixtures/project/cats/dto/create-cat.dto.ts
  test/plugin/fixtures/serialized-meta.fixture.ts
Labels: bug

#1434 fix(): move modifiers properties to items object on array type
  lib/services/swagger-types-mapper.ts
  test/explorer/swagger-explorer.spec.ts
  test/services/fixtures/create-user.dto.ts
  test/services/schema-object-factory.spec.ts
Labels: enhancement

#2233 Api callbacks decorator
  e2e/api-spec.json
  e2e/src/cats/cats.controller.ts
  e2e/validate-schema.e2e-spec.ts
  lib/constants.ts
  lib/decorators/api-callbacks.decorator.ts
  lib/decorators/index.ts
  lib/explorers/api-callbacks.explorer.ts
  lib/extra/swagger-shim.ts
  lib/interfaces/callback-object.interface.ts
  lib/interfaces/denormalized-doc-resolvers.interface.ts
  lib/swagger-explorer.ts
Labels: feature

#3123 feat: introduce enum schema attribute
  e2e/api-spec.json
  e2e/src/cats/cats.controller.ts
  e2e/src/cats/classes/cat.class.ts
  e2e/src/cats/dto/create-cat.dto.ts
  lib/decorators/api-param.decorator.ts
  lib/decorators/api-property.decorator.ts
  lib/decorators/api-query.decorator.ts
  lib/interfaces/enum-schema-attributes.interface.ts
  lib/interfaces/schema-object-metadata.interface.ts
  lib/services/parameter-metadata-accessor.ts
  lib/services/schema-object-factory.ts
  lib/services/swagger-types-mapper.ts
  lib/utils/enum.utils.ts
  test/explorer/swagger-explorer.spec.ts
  test/services/schema-object-factory.spec.ts
Labels: enhancement

#2877 fix(): Updated types for Specific ApiResponse decorator options to omit status
  lib/decorators/api-response.decorator.ts
  test/decorators/api-response.decorator.spec.ts
Labels: status: blocked, breaking change, type: enhancement :wolf:

#3129 feat: Add schema support for more option keys
  e2e/api-spec.json
  e2e/src/cats/dto/pagination-query.dto.ts
  lib/services/swagger-types-mapper.ts
  test/plugin/fixtures/project/cats/dto/pagination-query.dto.ts
  test/plugin/fixtures/serialized-meta.fixture.ts
Labels: enhancement
