Repository nestjs/swagger, pull requests merged in 2025-01, with the labels that each got.

#3223 fix: swagger crashed while using any Param/Query/Body decorator in a monorepo with pnpm
  lib/services/parameter-metadata-accessor.ts
Labels: bug

#3232 fix: missing ApiProperty enum undefined handling
  lib/decorators/api-property.decorator.ts
  test/services/schema-object-factory.spec.ts
Labels: bug

#3199 release: version 11.0.0
  .circleci/config.yml
  e2e/api-spec.json
  e2e/express.e2e-spec.ts
  e2e/fastify.e2e-spec.ts
  e2e/src/app.controller.ts
  e2e/src/cats/cats.controller.ts
  e2e/src/express.controller.ts
  e2e/src/fastify.controller.ts
  e2e/validate-schema.e2e-spec.ts
  lib/swagger-explorer.ts
  lib/swagger-scanner.ts
  lib/swagger-transformer.ts
  package-lock.json
  package.json
Labels: release

#3235 feat: make generated require() ESM compatible
  lib/plugin/utils/plugin-utils.ts
  test/plugin/fixtures/parameter-property.dto.ts
  test/plugin/fixtures/serialized-meta.fixture.ts
Labels: enhancement

#3264 fix: incorrect IsUuid class-validator decorator
  lib/services/decorators-properties.ts
  test/plugin/fixtures/create-cat.dto.ts
Labels: bug
