Repository nestjs/swagger, pull requests merged in 2025-04, with the labels that each got.

#3369 fix: recursive schema reference handling #3368
  lib/services/schema-object-factory.ts
  test/services/schema-object-factory.spec.ts
Labels: bug

#3362 feat: make generated require() ESM compatible
  lib/plugin/merge-options.ts
  lib/plugin/utils/plugin-utils.ts
  lib/plugin/visitors/controller-class.visitor.ts
  lib/plugin/visitors/model-class.visitor.ts
  lib/plugin/visitors/readonly.visitor.ts
  package.json
  test/plugin/fixtures/create-option.ts
  test/plugin/fixtures/parameter-property.dto.ts
  test/plugin/fixtures/serialized-meta-esm.fixture.ts
  test/plugin/model-class-visitor.spec.ts
  test/plugin/readonly-visitor.spec.ts
Labels: enhancement

#3400 feat(schema): add duplicate DTO detection in schema exploration
  lib/services/schema-object-factory.ts
  test/services/schema-object-factory.spec.ts
Labels: type: enhancement :wolf:

#3413 fix: type import syntax for ApiResponse in esmCompatible
  lib/plugin/utils/plugin-utils.ts
  test/plugin/fixtures/parameter-property.dto.ts
Labels: bug

#3423 feat(swagger-plugin): add skipDefaultValues option to omit unspecified default fields and corresponding test
  lib/plugin/merge-options.ts
  lib/plugin/visitors/model-class.visitor.ts
  test/plugin/fixtures/create-option.ts
  test/plugin/model-class-visitor.spec.ts
Labels: enhancement
